{% set name = "proplot" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7595fe8d785ddc2d43e8c6c055cca441650a5d1eac4c9d15c496574479c7d6f5

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
    - setuptools >=30.3.0
  run:
    - python >=3.6
    - matplotlib-base

test:
  imports:
    - proplot

about:
  home: https://proplot.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A comprehensive, easy-to-use matplotlib wrapper for making beautiful, publication-quality graphics.
  dev_url: https://github.com/lukelbd/proplot

extra:
  recipe-maintainers:
    - hmaarrfk
    - lukelbd
